/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/3d-models/rocket.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rocket.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.513, -0.784, 0.067]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, Math.PI / 4, 0]}>
              <group position={[0, 3.274, 59.551]}>
                <mesh geometry={nodes['Rocket_Ship_01_Material_#27_0'].geometry} material={materials.Material_27} />
                <mesh geometry={nodes['Rocket_Ship_01_Material_#28_0'].geometry} material={materials.Material_28} />
                <mesh geometry={nodes['Rocket_Ship_01_Material_#29_0'].geometry} material={materials.Material_29} />
                <mesh geometry={nodes['Rocket_Ship_01_Material_#30_0'].geometry} material={materials.Material_30} />
                <mesh geometry={nodes['Rocket_Ship_01_Material_#42_0'].geometry} material={materials.Material_42} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rocket.glb')
